# Generated by Django 5.2.8 on 2025-11-18 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RadiusClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("shortname", models.CharField(max_length=50, unique=True)),
                ("nas_type", models.CharField(default="other", max_length=50)),
                ("ip_address", models.GenericIPAddressField(unique=True)),
                ("secret", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "radius_clients",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RadiusServer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("host", models.CharField(max_length=255)),
                ("auth_port", models.IntegerField(default=1812)),
                ("acct_port", models.IntegerField(default=1813)),
                ("secret", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "timeout",
                    models.IntegerField(default=5, help_text="Timeout in seconds"),
                ),
                ("retries", models.IntegerField(default=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "radius_servers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RadiusAuthLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(db_index=True, max_length=255)),
                ("mac_address", models.CharField(blank=True, max_length=17, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("nas_ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("nas_port", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("accept", "Accept"),
                            ("reject", "Reject"),
                            ("challenge", "Challenge"),
                            ("error", "Error"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reply_message", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("request_data", models.JSONField(blank=True, null=True)),
                ("response_data", models.JSONField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auth_logs",
                        to="radius.radiusserver",
                    ),
                ),
            ],
            options={
                "db_table": "radius_auth_logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["username", "timestamp"],
                        name="radius_auth_usernam_440c2f_idx",
                    ),
                    models.Index(
                        fields=["status", "timestamp"],
                        name="radius_auth_status_4d2c7b_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RadiusAccounting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(db_index=True, max_length=255)),
                ("username", models.CharField(db_index=True, max_length=255)),
                ("mac_address", models.CharField(blank=True, max_length=17, null=True)),
                (
                    "framed_ip_address",
                    models.GenericIPAddressField(blank=True, null=True),
                ),
                ("nas_ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("nas_port", models.IntegerField(blank=True, null=True)),
                (
                    "status_type",
                    models.CharField(
                        choices=[
                            ("start", "Start"),
                            ("stop", "Stop"),
                            ("interim-update", "Interim Update"),
                            ("accounting-on", "Accounting On"),
                            ("accounting-off", "Accounting Off"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "termination_cause",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("user-request", "User Request"),
                            ("lost-carrier", "Lost Carrier"),
                            ("idle-timeout", "Idle Timeout"),
                            ("session-timeout", "Session Timeout"),
                            ("admin-reset", "Admin Reset"),
                            ("port-error", "Port Error"),
                            ("nas-error", "NAS Error"),
                            ("nas-request", "NAS Request"),
                            ("nas-reboot", "NAS Reboot"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "session_time",
                    models.IntegerField(
                        default=0, help_text="Session duration in seconds"
                    ),
                ),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("stop_time", models.DateTimeField(blank=True, null=True)),
                ("input_octets", models.BigIntegerField(default=0)),
                ("output_octets", models.BigIntegerField(default=0)),
                ("input_packets", models.BigIntegerField(default=0)),
                ("output_packets", models.BigIntegerField(default=0)),
                ("input_gigawords", models.BigIntegerField(default=0)),
                ("output_gigawords", models.BigIntegerField(default=0)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("raw_data", models.JSONField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounting_records",
                        to="radius.radiusserver",
                    ),
                ),
            ],
            options={
                "db_table": "radius_accounting",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["session_id", "timestamp"],
                        name="radius_acco_session_a41b68_idx",
                    ),
                    models.Index(
                        fields=["username", "timestamp"],
                        name="radius_acco_usernam_a1c309_idx",
                    ),
                    models.Index(
                        fields=["status_type", "timestamp"],
                        name="radius_acco_status__e7b240_idx",
                    ),
                ],
            },
        ),
    ]
