# Generated by Django 5.2.8 on 2025-12-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radius', '0002_freeradius_tables'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='radcheck',
            new_name='radcheck_usernam_d6e966_idx',
            old_name='radcheck_username_idx',
        ),
        migrations.RenameIndex(
            model_name='radgroupcheck',
            new_name='radgroupche_groupna_7b4e9c_idx',
            old_name='radgroupcheck_groupname_idx',
        ),
        migrations.RenameIndex(
            model_name='radgroupreply',
            new_name='radgrouprep_groupna_1a2f37_idx',
            old_name='radgroupreply_groupname_idx',
        ),
        migrations.RenameIndex(
            model_name='radpostauth',
            new_name='radpostauth_usernam_20f4db_idx',
            old_name='radpostauth_username_idx',
        ),
        migrations.RenameIndex(
            model_name='radreply',
            new_name='radreply_usernam_531b3d_idx',
            old_name='radreply_username_idx',
        ),
        migrations.RenameIndex(
            model_name='radusergroup',
            new_name='radusergrou_usernam_2655c9_idx',
            old_name='radusergroup_username_idx',
        ),
        migrations.RenameIndex(
            model_name='radusergroup',
            new_name='radusergrou_groupna_d41522_idx',
            old_name='radusergroup_groupname_idx',
        ),
        migrations.AddField(
            model_name='radcheck',
            name='statut',
            field=models.BooleanField(default=True, help_text="Statut de l'utilisateur (1=activé, 0=désactivé) - contrôle l'accès Internet via RADIUS"),
        ),
    ]
