# Generated by Django 5.2.8 on 2025-12-25 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radius', '0005_add_quota_to_radcheck'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadAcct',
            fields=[
                ('radacctid', models.BigAutoField(db_column='radacctid', primary_key=True, serialize=False)),
                ('acctsessionid', models.CharField(db_column='acctsessionid', db_index=True, max_length=64)),
                ('acctuniqueid', models.CharField(db_column='acctuniqueid', max_length=32, unique=True)),
                ('username', models.CharField(db_index=True, max_length=64)),
                ('nasipaddress', models.GenericIPAddressField(db_column='nasipaddress')),
                ('nasportid', models.CharField(blank=True, db_column='nasportid', max_length=15, null=True)),
                ('nasporttype', models.CharField(blank=True, db_column='nasporttype', max_length=32, null=True)),
                ('acctstarttime', models.DateTimeField(blank=True, db_column='acctstarttime', db_index=True, null=True)),
                ('acctupdatetime', models.DateTimeField(blank=True, db_column='acctupdatetime', null=True)),
                ('acctstoptime', models.DateTimeField(blank=True, db_column='acctstoptime', db_index=True, null=True)),
                ('acctsessiontime', models.IntegerField(blank=True, db_column='acctsessiontime', help_text='Session duration in seconds', null=True)),
                ('acctauthentic', models.CharField(blank=True, db_column='acctauthentic', max_length=32, null=True)),
                ('connectinfo_start', models.CharField(blank=True, db_column='connectinfo_start', max_length=50, null=True)),
                ('connectinfo_stop', models.CharField(blank=True, db_column='connectinfo_stop', max_length=50, null=True)),
                ('acctinputoctets', models.BigIntegerField(blank=True, db_column='acctinputoctets', default=0, null=True)),
                ('acctoutputoctets', models.BigIntegerField(blank=True, db_column='acctoutputoctets', default=0, null=True)),
                ('calledstationid', models.CharField(blank=True, db_column='calledstationid', max_length=50, null=True)),
                ('callingstationid', models.CharField(blank=True, db_column='callingstationid', max_length=50, null=True)),
                ('acctterminatecause', models.CharField(blank=True, db_column='acctterminatecause', max_length=32, null=True)),
                ('servicetype', models.CharField(blank=True, db_column='servicetype', max_length=32, null=True)),
                ('framedprotocol', models.CharField(blank=True, db_column='framedprotocol', max_length=32, null=True)),
                ('framedipaddress', models.GenericIPAddressField(blank=True, db_column='framedipaddress', db_index=True, null=True)),
            ],
            options={
                'db_table': 'radacct',
                'ordering': ['-acctstarttime'],
                'managed': False,
            },
        ),
    ]
