# Generated by Django 5.2.8 on 2025-11-18 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MikrotikRouter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("host", models.CharField(max_length=255)),
                ("port", models.IntegerField(default=8728)),
                ("username", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                ("use_ssl", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "mikrotik_routers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MikrotikHotspotUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                ("mac_address", models.CharField(blank=True, max_length=17, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "uptime_limit",
                    models.IntegerField(
                        blank=True, help_text="Uptime limit in seconds", null=True
                    ),
                ),
                ("bytes_in_limit", models.BigIntegerField(blank=True, null=True)),
                ("bytes_out_limit", models.BigIntegerField(blank=True, null=True)),
                (
                    "rate_limit",
                    models.CharField(
                        blank=True, help_text="e.g., 512k/2M", max_length=100, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_disabled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_sync", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mikrotik_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "router",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hotspot_users",
                        to="mikrotik.mikrotikrouter",
                    ),
                ),
            ],
            options={
                "db_table": "mikrotik_hotspot_users",
                "ordering": ["-created_at"],
                "unique_together": {("router", "username")},
            },
        ),
        migrations.CreateModel(
            name="MikrotikLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("debug", "Debug"),
                        ],
                        default="info",
                        max_length=20,
                    ),
                ),
                ("operation", models.CharField(max_length=100)),
                ("message", models.TextField()),
                ("details", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "router",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="mikrotik.mikrotikrouter",
                    ),
                ),
            ],
            options={
                "db_table": "mikrotik_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["router", "created_at"],
                        name="mikrotik_lo_router__0d1db6_idx",
                    ),
                    models.Index(
                        fields=["level", "created_at"],
                        name="mikrotik_lo_level_ca10b8_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MikrotikActiveConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=255, unique=True)),
                ("username", models.CharField(max_length=255)),
                ("mac_address", models.CharField(db_index=True, max_length=17)),
                ("ip_address", models.GenericIPAddressField()),
                ("uptime", models.IntegerField(default=0)),
                ("bytes_in", models.BigIntegerField(default=0)),
                ("bytes_out", models.BigIntegerField(default=0)),
                ("packets_in", models.BigIntegerField(default=0)),
                ("packets_out", models.BigIntegerField(default=0)),
                ("login_time", models.DateTimeField()),
                ("last_update", models.DateTimeField(auto_now=True)),
                (
                    "hotspot_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="mikrotik.mikrotikhotspotuser",
                    ),
                ),
                (
                    "router",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="active_connections",
                        to="mikrotik.mikrotikrouter",
                    ),
                ),
            ],
            options={
                "db_table": "mikrotik_active_connections",
                "ordering": ["-login_time"],
                "indexes": [
                    models.Index(
                        fields=["router", "mac_address"],
                        name="mikrotik_ac_router__408c72_idx",
                    ),
                    models.Index(
                        fields=["session_id"], name="mikrotik_ac_session_a21d76_idx"
                    ),
                ],
            },
        ),
    ]
