# Generated by Django 5.2.8 on 2025-11-21 16:35

import django.db.models.deletion
from django.db import migrations, models


def get_default_role_id():
    """
    Stub function for migration compatibility.
    This function is preserved to avoid import errors when loading migrations,
    but it's never actually called since this migration has already been applied.
    """
    return 1  # Fallback ID, should never be called in practice


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('admin', 'Administrator'), ('user', 'User')], db_index=True, max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'roles',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(default=get_default_role_id, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='core.role'),
        ),
    ]
