# Generated by Django 5.2.8 on 2025-11-23 20:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_role_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_limit', models.BigIntegerField(default=5368709120, help_text='Daily limit in bytes (default 5GB)')),
                ('weekly_limit', models.BigIntegerField(default=32212254720, help_text='Weekly limit in bytes (default 30GB)')),
                ('monthly_limit', models.BigIntegerField(default=128849018880, help_text='Monthly limit in bytes (default 120GB)')),
                ('used_today', models.BigIntegerField(default=0)),
                ('used_week', models.BigIntegerField(default=0)),
                ('used_month', models.BigIntegerField(default=0)),
                ('last_daily_reset', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_weekly_reset', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_monthly_reset', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('is_exceeded', models.BooleanField(default=False, help_text='True if any quota is exceeded')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quota', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_quotas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlockedSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(db_index=True, help_text='Domain or URL to block/allow', max_length=255, unique=True)),
                ('type', models.CharField(choices=[('blacklist', 'Blacklist'), ('whitelist', 'Whitelist')], default='blacklist', max_length=20)),
                ('reason', models.CharField(blank=True, help_text='Reason for blocking/allowing', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_sites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'blocked_sites',
                'ordering': ['-added_date'],
                'indexes': [models.Index(fields=['type', 'is_active'], name='blocked_sit_type_7f32e2_idx')],
            },
        ),
    ]
