# Generated by Django 5.2.8 on 2025-11-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0004_convert_role_to_charfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_pre_registered",
            field=models.BooleanField(
                default=False,
                help_text="Utilisateur pré-enregistré par un administrateur",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="matricule",
            field=models.CharField(
                blank=True,
                help_text="Matricule de l'étudiant",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="promotion",
            field=models.CharField(
                blank=True,
                help_text="Promotion de l'étudiant (ex: ING3, L1, etc.)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="registration_completed",
            field=models.BooleanField(
                default=False, help_text="L'utilisateur a complété son inscription"
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                fields=("first_name", "last_name", "promotion", "matricule"),
                name="unique_student_identity",
            ),
        ),
    ]
