# Generated by Django 5.2.8 on 2025-12-04 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_cleartext_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Code de la promotion (ex: ING3, L1, M2, X2027)', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Nom complet de la promotion', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description de la promotion', null=True)),
                ('year', models.IntegerField(blank=True, help_text='Année de la promotion', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Promotion active (si False, tous les utilisateurs de cette promotion sont désactivés)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
                'db_table': 'promotions',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='is_radius_enabled',
            field=models.BooleanField(default=True, help_text="Utilisateur activé/désactivé dans RADIUS (contrôle l'accès Internet)"),
        ),
        migrations.AlterField(
            model_name='user',
            name='promotion',
            field=models.ForeignKey(blank=True, help_text="Promotion de l'étudiant", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.promotion'),
        ),
    ]
