# Generated by Django 5.2.8 on 2025-12-09 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_promotion_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_radius_enabled',
        ),
    ]
