# Generated by Django 5.2.8 on 2025-12-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_back_is_radius_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_radius_activated',
            field=models.BooleanField(default=False, help_text="Indique si l'utilisateur a été créé dans RADIUS (provisionné une fois par admin)"),
        ),
    ]
