# Generated by Django 5.2.8 on 2025-12-11 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_user_is_radius_activated'),
        ('core', '0014_add_profile_usage_history_alerts'),
    ]

    operations = [
    ]
