# Generated by Django 5.2.8 on 2025-12-11 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_convert_bandwidth_kbps_to_mbps'),
        ('core', '0015_merge_20251211_0849'),
    ]

    operations = [
    ]
