# Generated by Django 5.2.8 on 2025-12-11 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_merge_20251211_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bandwidth_download',
            field=models.IntegerField(default=10, help_text='Bande passante download en Mbps (ex: 10 = 10 Mbps)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bandwidth_upload',
            field=models.IntegerField(default=5, help_text='Bande passante upload en Mbps (ex: 5 = 5 Mbps)'),
        ),
        migrations.CreateModel(
            name='UserDisconnectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('quota_exceeded', 'Quota de données dépassé'), ('session_expired', 'Session expirée'), ('daily_limit', 'Limite journalière atteinte'), ('weekly_limit', 'Limite hebdomadaire atteinte'), ('monthly_limit', 'Limite mensuelle atteinte'), ('idle_timeout', "Délai d'inactivité dépassé"), ('validity_expired', 'Durée de validité expirée'), ('manual', 'Désactivation manuelle par admin')], help_text='Raison de la déconnexion', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Description détaillée de la raison')),
                ('disconnected_at', models.DateTimeField(auto_now_add=True, help_text='Date et heure de la déconnexion')),
                ('reconnected_at', models.DateTimeField(blank=True, help_text='Date et heure de la reconnexion (si réactivé)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text="True si l'utilisateur est toujours déconnecté")),
                ('quota_used', models.BigIntegerField(blank=True, help_text='Quota utilisé en octets au moment de la déconnexion', null=True)),
                ('quota_limit', models.BigIntegerField(blank=True, help_text='Limite de quota en octets', null=True)),
                ('session_duration', models.IntegerField(blank=True, help_text='Durée de la session en secondes', null=True)),
                ('reconnected_by', models.ForeignKey(blank=True, help_text="Admin qui a réactivé l'utilisateur", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconnections_performed', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='Utilisateur concerné', on_delete=django.db.models.deletion.CASCADE, related_name='disconnection_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de déconnexion',
                'verbose_name_plural': 'Logs de déconnexions',
                'db_table': 'user_disconnection_logs',
                'ordering': ['-disconnected_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='user_discon_user_id_724674_idx'), models.Index(fields=['disconnected_at'], name='user_discon_disconn_81555e_idx'), models.Index(fields=['reason'], name='user_discon_reason_36fee6_idx')],
            },
        ),
    ]
