# Generated by Django 5.2.8 on 2025-12-12 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_user_disconnection_log'),
        ('core', '0017_alter_profile_bandwidth_download_and_more'),
    ]

    operations = [
    ]
