# Generated by Django 5.2.8 on 2025-12-25 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_user_is_radius_activated'),
        ('core', '0017_add_validators_to_profile_and_alerts'),
    ]

    operations = [
    ]
