# Generated by Django 5.2.8 on 2025-12-25 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_merge_20251225_0921'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdisconnectionlog',
            options={'ordering': ['-disconnected_at'], 'verbose_name': 'Log de déconnexion', 'verbose_name_plural': 'Logs de déconnexions'},
        ),
        migrations.RenameIndex(
            model_name='blockedsite',
            new_name='blocked_sit_sync_st_535f65_idx',
            old_name='blocked_sit_sync_st_idx',
        ),
        migrations.RenameIndex(
            model_name='blockedsite',
            new_name='blocked_sit_categor_e60468_idx',
            old_name='blocked_sit_categor_idx',
        ),
        migrations.RenameIndex(
            model_name='userdisconnectionlog',
            new_name='user_discon_user_id_724674_idx',
            old_name='idx_user_active',
        ),
        migrations.RenameIndex(
            model_name='userdisconnectionlog',
            new_name='user_discon_disconn_81555e_idx',
            old_name='idx_disconnected_at',
        ),
        migrations.RenameIndex(
            model_name='userdisconnectionlog',
            new_name='user_discon_reason_36fee6_idx',
            old_name='idx_reason',
        ),
        migrations.AlterField(
            model_name='userdisconnectionlog',
            name='description',
            field=models.TextField(blank=True, help_text='Description détaillée de la raison'),
        ),
        migrations.AlterField(
            model_name='userdisconnectionlog',
            name='disconnected_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Date et heure de la déconnexion'),
        ),
        migrations.AlterField(
            model_name='userdisconnectionlog',
            name='is_active',
            field=models.BooleanField(default=True, help_text="True si l'utilisateur est toujours déconnecté"),
        ),
        migrations.AlterField(
            model_name='userdisconnectionlog',
            name='quota_limit',
            field=models.BigIntegerField(blank=True, help_text='Limite de quota en octets', null=True),
        ),
        migrations.AlterField(
            model_name='userdisconnectionlog',
            name='quota_used',
            field=models.BigIntegerField(blank=True, help_text='Quota utilisé en octets au moment de la déconnexion', null=True),
        ),
        migrations.AlterField(
            model_name='userdisconnectionlog',
            name='reconnected_at',
            field=models.DateTimeField(blank=True, help_text='Date et heure de la reconnexion (si réactivé)', null=True),
        ),
        migrations.AlterField(
            model_name='userdisconnectionlog',
            name='reconnected_by',
            field=models.ForeignKey(blank=True, help_text="Admin qui a réactivé l'utilisateur", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconnections_performed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userdisconnectionlog',
            name='session_duration',
            field=models.IntegerField(blank=True, help_text='Durée de la session en secondes', null=True),
        ),
        migrations.AlterField(
            model_name='userdisconnectionlog',
            name='user',
            field=models.ForeignKey(help_text='Utilisateur concerné', on_delete=django.db.models.deletion.CASCADE, related_name='disconnection_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
