# Generated by Django 5.2.8 on 2026-01-05 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_userdisconnectionlog_options_and_more'),
        ('core', '0020_add_performance_indexes'),
    ]

    operations = [
    ]
